### ISSUE TITLE
PhoneGap

### ISSUE THREAD

**Issue by HanrichPotgieter** [FrikkieSnyman/COS301_GroupProject#12]
I had to make another copy of the bootsrap.css files and moved it to the roo/bin/ folder. This had to happen beacuse phoneg gap copies the index.html file from ./www directory into the root directory. Then obviously the html document cannot find its dependancies. I am not sure how we can resolve this but we will definitely require a better solution.

Also I had to rename the ./public folder to ./www as this was required by phone gap. 

lastly I had to rename the ./documentation/softwarere........ to a shorter name. Phonegap does not like huge document names.
Thankfully the app works now but we do require a better solution.

**Comment by StaceyBaror** [comment]
Noted

Kind regards
Stacey
